version: "3.7"
services:
  dp_webclient:
    build:
      context: .
      dockerfile: Dockerfile.WebClient
      args:
        configuration: docker_local
    image: dp/webclient:latest
    ports:
      - "80:80"
    depends_on:
      - "dp_webapi"
  dp_webapi:
    build:
      context: .
      dockerfile: Dockerfile.WebApi
      args:
        configuration: docker_local
    image: dp/webapi:latest
    ports:
      - "5000:80"
    environment:
      - RedisHost=host.docker.internal:6379
    depends_on:
      - "redis"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

