version: "3.7"
services:
  dp_webclient:
    build:
      context: .
      dockerfile: Dockerfile.WebClient
      args:
        configuration: docker_local
    image: dp/webclient:latest
    ports:
      - "80:80"
    depends_on:
      - "dp_webapi_balancer"
  dp_webapi:
    build:
      context: .
      dockerfile: Dockerfile.WebApi
      args:
        configuration: docker_local
    image: dp/webapi:latest
    ports:
      - "80"
    environment:
      - RedisHost=dp_redis:6379
    depends_on:
      - "dp_redis"
  dp_redis:
    image: redis:latest
    ports:
      - "6379:6379"
  dp_webapi_balancer:
    image: nginx:1.15
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - dp_webapi
    ports:
      - "5000:5000"
